@echo off

cd /d E:\ungoogled\chromium\src

git checkout .
git -C third_party/clang-format/script checkout .
git -C chrome/browser/resources/preinstalled_web_apps/internal checkout .
git -C chrome/installer/mac/third_party/xz/xz checkout .
git -C third_party/libc++/src checkout .
git -C third_party/libc++abi/src checkout .
git -C third_party/libunwind/src checkout .
git -C third_party/llvm-libc/src checkout .
git -C chrome/test/data/autofill/captured_sites/artifacts checkout .
git -C chrome/test/data/password/captured_sites/artifacts checkout .
git -C chrome/test/data/perf/canvas_bench checkout .
git -C chrome/test/data/perf/frame_rate/content checkout .
git -C chrome/test/data/xr/webvr_info checkout .
git -C clank checkout .
git -C docs/website checkout .
git -C ios/third_party/earl_grey2/src checkout .
git -C ios/third_party/edo/src checkout .
git -C ios/third_party/gtx/src checkout .
git -C ios/third_party/lottie/src checkout .
git -C ios/third_party/material_components_ios/src checkout .
git -C ios/third_party/material_font_disk_loader_ios/src checkout .
git -C ios/third_party/material_internationalization_ios/src checkout .
git -C ios/third_party/material_roboto_font_loader_ios/src checkout .
git -C ios/third_party/material_sprited_animation_view_ios/src checkout .
git -C ios/third_party/material_text_accessibility_ios/src checkout .
git -C ios/third_party/motion_interchange_objc/src checkout .
git -C ios/third_party/motion_animator_objc/src checkout .
git -C ios/third_party/motion_transitioning_objc/src checkout .
git -C ios/third_party/ochamcrest/src checkout .
git -C ios/third_party/webkit/src checkout .
git -C media/cdm/api checkout .
git -C native_client checkout .
git -C net/third_party/quiche/src checkout .
git -C testing/libfuzzer/fuzzers/wasm_corpus checkout .
git -C third_party/accessibility_test_framework/src checkout .
git -C third_party/androidx_javascriptengine/src checkout .
git -C third_party/angle/third_party/glmark2/src checkout .
git -C third_party/angle/third_party/rapidjson/src checkout .
git -C third_party/angle checkout .
git -C third_party/anonymous_tokens/src checkout .
git -C third_party/content_analysis_sdk/src checkout .
git -C third_party/dav1d/libdav1d checkout .
git -C third_party/dawn/third_party/dxc checkout .
git -C third_party/dawn/third_party/glfw checkout .
git -C third_party/dawn/third_party/khronos/EGL-Registry checkout .
git -C third_party/dawn/third_party/khronos/OpenGL-Registry checkout .
git -C third_party/dawn/third_party/webgpu-cts checkout .
git -C third_party/dawn checkout .
git -C third_party/highway/src checkout .
git -C third_party/apache-portable-runtime/src checkout .
git -C third_party/barhopper checkout .
git -C third_party/google_benchmark/src checkout .
git -C third_party/boringssl/src checkout .
git -C third_party/breakpad/breakpad checkout .
git -C third_party/cast_core/public/src checkout .
git -C third_party/catapult checkout .
git -C third_party/ced/src checkout .
git -C third_party/chromium-variations checkout .
git -C third_party/chromevox/third_party/sre/src checkout .
git -C third_party/chromite checkout .
git -C third_party/cld_3/src checkout .
git -C third_party/colorama/src checkout .
git -C third_party/cpu_features/src checkout .
git -C third_party/cpuinfo/src checkout .
git -C third_party/crc32c/src checkout .
git -C third_party/cros_system_api checkout .
git -C third_party/crossbench checkout .
git -C third_party/depot_tools checkout .
git -C third_party/devtools-frontend/src checkout .
git -C third_party/devtools-frontend-internal checkout .
git -C third_party/dom_distiller_js/dist checkout .
git -C third_party/eigen3/src checkout .
git -C third_party/emoji-metadata/src checkout .
git -C third_party/farmhash/src checkout .
git -C third_party/fast_float/src checkout .
git -C third_party/ffmpeg checkout .
git -C third_party/flac checkout .
git -C third_party/flatbuffers/src checkout .
git -C third_party/fontconfig/src checkout .
git -C third_party/fp16/src checkout .
git -C third_party/gemmlowp/src checkout .
git -C third_party/grpc/src checkout .
git -C third_party/freetype/src checkout .
git -C third_party/freetype-testing/src checkout .
git -C third_party/fxdiv/src checkout .
git -C third_party/harfbuzz-ng/src checkout .
git -C third_party/ink/src checkout .
git -C third_party/ink_stroke_modeler/src checkout .
git -C third_party/instrumented_libs checkout .
git -C third_party/jszip/src checkout .
git -C third_party/emoji-segmenter/src checkout .
git -C third_party/ots/src checkout .
git -C third_party/libgav1/src checkout .
git -C third_party/google_toolbox_for_mac/src checkout .
git -C third_party/google-truth/src checkout .
git -C third_party/googletest/src checkout .
git -C third_party/gperf checkout .
git -C third_party/cardboard/src checkout .
git -C third_party/arcore-android-sdk/src checkout .
git -C third_party/hunspell_dictionaries checkout .
git -C third_party/icu checkout .
git -C third_party/javalang/src checkout .
git -C third_party/jsoncpp/source checkout .
git -C third_party/junit/src checkout .
git -C third_party/leveldatabase/src checkout .
git -C third_party/libFuzzer/src checkout .
git -C third_party/fuzztest/src checkout .
git -C third_party/domato/src checkout .
git -C third_party/libaddressinput/src checkout .
git -C third_party/libaom/source/libaom checkout .
git -C third_party/libavif/src checkout .
git -C third_party/crabbyavif/src checkout .
git -C third_party/nearby/src checkout .
git -C third_party/beto-core/src checkout .
git -C third_party/securemessage/src checkout .
git -C third_party/speedometer/v3.0 checkout .
git -C third_party/speedometer/main checkout .
git -C third_party/ukey2/src checkout .
git -C third_party/cros-components/src checkout .
git -C third_party/libdrm/src checkout .
git -C third_party/expat/src checkout .
git -C third_party/libipp/libipp checkout .
git -C third_party/libjpeg_turbo checkout .
git -C third_party/liblouis/src checkout .
git -C third_party/libphonenumber/dist checkout .
git -C third_party/libprotobuf-mutator/src checkout .
git -C third_party/libsrtp checkout .
git -C third_party/libsync/src checkout .
git -C third_party/libunwindstack checkout .
git -C third_party/libvpx/source/libvpx checkout .
git -C third_party/libwebm/source checkout .
git -C third_party/libwebp/src checkout .
git -C third_party/libyuv checkout .
git -C third_party/lighttpd checkout .
git -C third_party/lss checkout .
git -C third_party/material_color_utilities/src checkout .
git -C third_party/material_design_icons/src checkout .
git -C third_party/microsoft_dxheaders/src checkout .
git -C third_party/minigbm/src checkout .
git -C third_party/nasm checkout .
git -C third_party/neon_2_sse/src checkout .
git -C third_party/netty-tcnative/src checkout .
git -C third_party/netty4/src checkout .
git -C third_party/openh264/src checkout .
git -C third_party/openscreen/src/buildtools checkout .
git -C third_party/openscreen/src checkout .
git -C third_party/openxr/src checkout .
git -C third_party/pdfium checkout .
git -C third_party/perfetto checkout .
git -C third_party/perl checkout .
git -C third_party/protobuf-javascript/src checkout .
git -C third_party/pthreadpool/src checkout .
git -C third_party/pyelftools checkout .
git -C third_party/quic_trace/src checkout .
git -C third_party/pywebsocket3/src checkout .
git -C third_party/re2/src checkout .
git -C third_party/requests/src checkout .
git -C third_party/ruy/src checkout .
git -C third_party/skia checkout .
git -C third_party/smhasher/src checkout .
git -C third_party/snappy/src checkout .
git -C third_party/sqlite/src checkout .
git -C third_party/swiftshader checkout .
git -C third_party/text-fragments-polyfill/src checkout .
git -C third_party/tflite/src checkout .
git -C third_party/vulkan-deps checkout .
git -C third_party/glslang/src checkout .
git -C third_party/spirv-cross/src checkout .
git -C third_party/spirv-headers/src checkout .
git -C third_party/spirv-tools/src checkout .
git -C third_party/vulkan-headers/src checkout .
git -C third_party/vulkan-loader/src checkout .
git -C third_party/vulkan-tools/src checkout .
git -C third_party/vulkan-utility-libraries/src checkout .
git -C third_party/vulkan-validation-layers/src checkout .
git -C third_party/vulkan_memory_allocator checkout .
git -C third_party/wayland/src checkout .
git -C third_party/wayland-protocols/src checkout .
git -C third_party/wayland-protocols/kde checkout .
git -C third_party/wayland-protocols/gtk checkout .
git -C third_party/webdriver/pylib checkout .
git -C third_party/webgl/src checkout .
git -C third_party/webgpu-cts/src checkout .
git -C third_party/webrtc checkout .
git -C third_party/wuffs/src checkout .
git -C third_party/weston/src checkout .
git -C third_party/wlcs/src checkout .
git -C third_party/xdg-utils checkout .
git -C third_party/xnnpack/src checkout .
git -C tools/page_cycler/acid3 checkout .
git -C third_party/zstd/src checkout .
git -C v8 checkout .
git -C internal checkout .
git -C third_party/android_prebuilts/build_tools checkout .
git -C chromeos/ash/resources/internal checkout .
git -C chromeos/assistant/internal checkout .
git -C build/fuchsia/internal checkout .
git -C chrome/app/theme/default_100_percent/google_chrome checkout .
git -C chrome/app/theme/default_200_percent/google_chrome checkout .
git -C chrome/app/theme/google_chrome checkout .
git -C chrome/browser/enterprise/connectors/internal checkout .
git -C chrome/browser/google/linkdoctor_internal checkout .
git -C chrome/browser/internal checkout .
git -C chrome/browser/media/engagement_internal checkout .
git -C chrome/browser/nearby_sharing/internal checkout .
git -C chrome/browser/platform_experience/win checkout .
git -C chrome/browser/request_header_integrity/internal checkout .
git -C chrome/browser/resources/downloads/internal checkout .
git -C chrome/browser/resources/settings/internal checkout .
git -C chrome/browser/spellchecker/internal checkout .
git -C chrome/elevation_service/internal checkout .
git -C chrome/installer/mac/internal checkout .
git -C chrome/test/data/firefox3_profile/searchplugins checkout .
git -C chrome/test/data/firefox3_searchplugins checkout .
git -C chrome/test/data/gpu/vt checkout .
git -C chrome/test/data/perf/frame_rate/private checkout .
git -C chrome/test/data/perf/private checkout .
git -C chrome/test/data/pdf_private checkout .
git -C chrome/test/media_router/internal checkout .
git -C chrome/tools/memory checkout .
git -C chrome/services/speech/internal checkout .
git -C chrome/updater/internal checkout .
git -C components/accessibility/internal checkout .
git -C components/autofill/core/browser/form_parsing/internal_resources checkout .
git -C components/crash/core/app/internal checkout .
git -C components/metrics/internal checkout .
git -C components/ntp_tiles/resources/internal checkout .
git -C components/optimization_guide/internal checkout .
git -C components/plus_addresses/resources/internal checkout .
git -C components/resources/default_100_percent/google_chrome checkout .
git -C components/resources/default_200_percent/google_chrome checkout .
git -C components/resources/default_300_percent/google_chrome checkout .
git -C components/site_isolation/internal checkout .
git -C components/test/data/autofill/heuristics-json/internal checkout .
git -C components/test/data/autofill/label-doms/internal checkout .
git -C components/vector_icons/google_chrome checkout .
git -C content/test/data/plugin checkout .
git -C google_apis/internal checkout .
git -C ios_internal checkout .
git -C remoting/host/installer/linux/internal checkout .
git -C remoting/internal checkout .
git -C remoting/test/internal checkout .
git -C remoting/tools/internal checkout .
git -C signing_keys checkout .
git -C skia/tools/clusterfuzz-data checkout .
git -C third_party/amd checkout .
git -C third_party/android_tools_internal checkout .
git -C third_party/widevine/cdm/chromeos checkout .
git -C third_party/widevine/cdm/linux checkout .
git -C third_party/widevine/cdm/mac checkout .
git -C third_party/widevine/cdm/win checkout .
git -C third_party/widevine/scripts checkout .
git -C third_party/widevine/test/license_server checkout .
git -C third_party/wix checkout .
git -C tools/perf/data checkout .
git -C ui/file_manager/internal checkout .
git -C ui/webui/internal checkout .
git -C webkit/data/bmp_decoder checkout .
git -C webkit/data/ico_decoder checkout .
git -C webkit/data/test_shell/plugins checkout .
git -C third_party/search_engines_data/resources checkout .
git -C third_party/speedometer/v3.1 checkout .
git -C third_party/webpagereplay checkout .
git -C third_party/compiler-rt/src checkout .
git -C third_party\dawn\third_party\webgpu-headers\src checkout .

git clean -df
git -C third_party/clang-format/script clean -df
git -C chrome/browser/resources/preinstalled_web_apps/internal clean -df
git -C chrome/installer/mac/third_party/xz/xz clean -df
git -C third_party/libc++/src clean -df
git -C third_party/libc++abi/src clean -df
git -C third_party/libunwind/src clean -df
git -C third_party/llvm-libc/src clean -df
git -C chrome/test/data/autofill/captured_sites/artifacts clean -df
git -C chrome/test/data/password/captured_sites/artifacts clean -df
git -C chrome/test/data/perf/canvas_bench clean -df
git -C chrome/test/data/perf/frame_rate/content clean -df
git -C chrome/test/data/xr/webvr_info clean -df
git -C clank clean -df
git -C docs/website clean -df
git -C ios/third_party/earl_grey2/src clean -df
git -C ios/third_party/edo/src clean -df
git -C ios/third_party/gtx/src clean -df
git -C ios/third_party/lottie/src clean -df
git -C ios/third_party/material_components_ios/src clean -df
git -C ios/third_party/material_font_disk_loader_ios/src clean -df
git -C ios/third_party/material_internationalization_ios/src clean -df
git -C ios/third_party/material_roboto_font_loader_ios/src clean -df
git -C ios/third_party/material_sprited_animation_view_ios/src clean -df
git -C ios/third_party/material_text_accessibility_ios/src clean -df
git -C ios/third_party/motion_interchange_objc/src clean -df
git -C ios/third_party/motion_animator_objc/src clean -df
git -C ios/third_party/motion_transitioning_objc/src clean -df
git -C ios/third_party/ochamcrest/src clean -df
git -C ios/third_party/webkit/src clean -df
git -C media/cdm/api clean -df
git -C native_client clean -df
git -C net/third_party/quiche/src clean -df
git -C testing/libfuzzer/fuzzers/wasm_corpus clean -df
git -C third_party/accessibility_test_framework/src clean -df
git -C third_party/androidx_javascriptengine/src clean -df
git -C third_party/angle/third_party/glmark2/src clean -df
git -C third_party/angle/third_party/rapidjson/src clean -df
git -C third_party/angle clean -df
git -C third_party/anonymous_tokens/src clean -df
git -C third_party/content_analysis_sdk/src clean -df
git -C third_party/dav1d/libdav1d clean -df
git -C third_party/dawn/third_party/dxc clean -df
git -C third_party/dawn/third_party/glfw clean -df
git -C third_party/dawn/third_party/khronos/EGL-Registry clean -df
git -C third_party/dawn/third_party/khronos/OpenGL-Registry clean -df
git -C third_party/dawn/third_party/webgpu-cts clean -df
git -C third_party/dawn clean -df
git -C third_party/highway/src clean -df
git -C third_party/apache-portable-runtime/src clean -df
git -C third_party/barhopper clean -df
git -C third_party/google_benchmark/src clean -df
git -C third_party/boringssl/src clean -df
git -C third_party/breakpad/breakpad clean -df
git -C third_party/cast_core/public/src clean -df
git -C third_party/catapult clean -df
git -C third_party/ced/src clean -df
git -C third_party/chromium-variations clean -df
git -C third_party/chromevox/third_party/sre/src clean -df
git -C third_party/chromite clean -df
git -C third_party/cld_3/src clean -df
git -C third_party/colorama/src clean -df
git -C third_party/cpu_features/src clean -df
git -C third_party/cpuinfo/src clean -df
git -C third_party/crc32c/src clean -df
git -C third_party/cros_system_api clean -df
git -C third_party/crossbench clean -df
git -C third_party/depot_tools clean -df
git -C third_party/devtools-frontend/src clean -df
git -C third_party/devtools-frontend-internal clean -df
git -C third_party/dom_distiller_js/dist clean -df
git -C third_party/eigen3/src clean -df
git -C third_party/emoji-metadata/src clean -df
git -C third_party/farmhash/src clean -df
git -C third_party/fast_float/src clean -df
git -C third_party/ffmpeg clean -df
git -C third_party/flac clean -df
git -C third_party/flatbuffers/src clean -df
git -C third_party/fontconfig/src clean -df
git -C third_party/fp16/src clean -df
git -C third_party/gemmlowp/src clean -df
git -C third_party/grpc/src clean -df
git -C third_party/freetype/src clean -df
git -C third_party/freetype-testing/src clean -df
git -C third_party/fxdiv/src clean -df
git -C third_party/harfbuzz-ng/src clean -df
git -C third_party/ink/src clean -df
git -C third_party/ink_stroke_modeler/src clean -df
git -C third_party/instrumented_libs clean -df
git -C third_party/jszip/src clean -df
git -C third_party/emoji-segmenter/src clean -df
git -C third_party/ots/src clean -df
git -C third_party/libgav1/src clean -df
git -C third_party/google_toolbox_for_mac/src clean -df
git -C third_party/google-truth/src clean -df
git -C third_party/googletest/src clean -df
git -C third_party/gperf clean -df
git -C third_party/cardboard/src clean -df
git -C third_party/arcore-android-sdk/src clean -df
git -C third_party/hunspell_dictionaries clean -df
git -C third_party/icu clean -df
git -C third_party/javalang/src clean -df
git -C third_party/jsoncpp/source clean -df
git -C third_party/junit/src clean -df
git -C third_party/leveldatabase/src clean -df
git -C third_party/libFuzzer/src clean -df
git -C third_party/fuzztest/src clean -df
git -C third_party/domato/src clean -df
git -C third_party/libaddressinput/src clean -df
git -C third_party/libaom/source/libaom clean -df
git -C third_party/libavif/src clean -df
git -C third_party/crabbyavif/src clean -df
git -C third_party/nearby/src clean -df
git -C third_party/beto-core/src clean -df
git -C third_party/securemessage/src clean -df
git -C third_party/speedometer/v3.0 clean -df
git -C third_party/speedometer/main clean -df
git -C third_party/ukey2/src clean -df
git -C third_party/cros-components/src clean -df
git -C third_party/libdrm/src clean -df
git -C third_party/expat/src clean -df
git -C third_party/libipp/libipp clean -df
git -C third_party/libjpeg_turbo clean -df
git -C third_party/liblouis/src clean -df
git -C third_party/libphonenumber/dist clean -df
git -C third_party/libprotobuf-mutator/src clean -df
git -C third_party/libsrtp clean -df
git -C third_party/libsync/src clean -df
git -C third_party/libunwindstack clean -df
git -C third_party/libvpx/source/libvpx clean -df
git -C third_party/libwebm/source clean -df
git -C third_party/libwebp/src clean -df
git -C third_party/libyuv clean -df
git -C third_party/lighttpd clean -df
git -C third_party/lss clean -df
git -C third_party/material_color_utilities/src clean -df
git -C third_party/material_design_icons/src clean -df
git -C third_party/microsoft_dxheaders/src clean -df
git -C third_party/minigbm/src clean -df
git -C third_party/nasm clean -df
git -C third_party/neon_2_sse/src clean -df
git -C third_party/netty-tcnative/src clean -df
git -C third_party/netty4/src clean -df
git -C third_party/openh264/src clean -df
git -C third_party/openscreen/src/buildtools clean -df
git -C third_party/openscreen/src clean -df
git -C third_party/openxr/src clean -df
git -C third_party/pdfium clean -df
git -C third_party/perfetto clean -df
git -C third_party/perl clean -df
git -C third_party/protobuf-javascript/src clean -df
git -C third_party/pthreadpool/src clean -df
git -C third_party/pyelftools clean -df
git -C third_party/quic_trace/src clean -df
git -C third_party/pywebsocket3/src clean -df
git -C third_party/re2/src clean -df
git -C third_party/requests/src clean -df
git -C third_party/ruy/src clean -df
git -C third_party/skia clean -df
git -C third_party/smhasher/src clean -df
git -C third_party/snappy/src clean -df
git -C third_party/sqlite/src clean -df
git -C third_party/swiftshader clean -df
git -C third_party/text-fragments-polyfill/src clean -df
git -C third_party/tflite/src clean -df
git -C third_party/vulkan-deps clean -df
git -C third_party/glslang/src clean -df
git -C third_party/spirv-cross/src clean -df
git -C third_party/spirv-headers/src clean -df
git -C third_party/spirv-tools/src clean -df
git -C third_party/vulkan-headers/src clean -df
git -C third_party/vulkan-loader/src clean -df
git -C third_party/vulkan-tools/src clean -df
git -C third_party/vulkan-utility-libraries/src clean -df
git -C third_party/vulkan-validation-layers/src clean -df
git -C third_party/vulkan_memory_allocator clean -df
git -C third_party/wayland/src clean -df
git -C third_party/wayland-protocols/src clean -df
git -C third_party/wayland-protocols/kde clean -df
git -C third_party/wayland-protocols/gtk clean -df
git -C third_party/webdriver/pylib clean -df
git -C third_party/webgl/src clean -df
git -C third_party/webgpu-cts/src clean -df
git -C third_party/webrtc clean -df
git -C third_party/wuffs/src clean -df
git -C third_party/weston/src clean -df
git -C third_party/wlcs/src clean -df
git -C third_party/xdg-utils clean -df
git -C third_party/xnnpack/src clean -df
git -C tools/page_cycler/acid3 clean -df
git -C third_party/zstd/src clean -df
git -C v8 clean -df
git -C internal clean -df
git -C third_party/android_prebuilts/build_tools clean -df
git -C chromeos/ash/resources/internal clean -df
git -C chromeos/assistant/internal clean -df
git -C build/fuchsia/internal clean -df
git -C chrome/app/theme/default_100_percent/google_chrome clean -df
git -C chrome/app/theme/default_200_percent/google_chrome clean -df
git -C chrome/app/theme/google_chrome clean -df
git -C chrome/browser/enterprise/connectors/internal clean -df
git -C chrome/browser/google/linkdoctor_internal clean -df
git -C chrome/browser/internal clean -df
git -C chrome/browser/media/engagement_internal clean -df
git -C chrome/browser/nearby_sharing/internal clean -df
git -C chrome/browser/platform_experience/win clean -df
git -C chrome/browser/request_header_integrity/internal clean -df
git -C chrome/browser/resources/downloads/internal clean -df
git -C chrome/browser/resources/settings/internal clean -df
git -C chrome/browser/spellchecker/internal clean -df
git -C chrome/elevation_service/internal clean -df
git -C chrome/installer/mac/internal clean -df
git -C chrome/test/data/firefox3_profile/searchplugins clean -df
git -C chrome/test/data/firefox3_searchplugins clean -df
git -C chrome/test/data/gpu/vt clean -df
git -C chrome/test/data/perf/frame_rate/private clean -df
git -C chrome/test/data/perf/private clean -df
git -C chrome/test/data/pdf_private clean -df
git -C chrome/test/media_router/internal clean -df
git -C chrome/tools/memory clean -df
git -C chrome/services/speech/internal clean -df
git -C chrome/updater/internal clean -df
git -C components/accessibility/internal clean -df
git -C components/autofill/core/browser/form_parsing/internal_resources clean -df
git -C components/crash/core/app/internal clean -df
git -C components/metrics/internal clean -df
git -C components/ntp_tiles/resources/internal clean -df
git -C components/optimization_guide/internal clean -df
git -C components/plus_addresses/resources/internal clean -df
git -C components/resources/default_100_percent/google_chrome clean -df
git -C components/resources/default_200_percent/google_chrome clean -df
git -C components/resources/default_300_percent/google_chrome clean -df
git -C components/site_isolation/internal clean -df
git -C components/test/data/autofill/heuristics-json/internal clean -df
git -C components/test/data/autofill/label-doms/internal clean -df
git -C components/vector_icons/google_chrome clean -df
git -C content/test/data/plugin clean -df
git -C google_apis/internal clean -df
git -C ios_internal clean -df
git -C remoting/host/installer/linux/internal clean -df
git -C remoting/internal clean -df
git -C remoting/test/internal clean -df
git -C remoting/tools/internal clean -df
git -C signing_keys clean -df
git -C skia/tools/clusterfuzz-data clean -df
git -C third_party/amd clean -df
git -C third_party/android_tools_internal clean -df
git -C third_party/widevine/cdm/chromeos clean -df
git -C third_party/widevine/cdm/linux clean -df
git -C third_party/widevine/cdm/mac clean -df
git -C third_party/widevine/cdm/win clean -df
git -C third_party/widevine/scripts clean -df
git -C third_party/widevine/test/license_server clean -df
git -C third_party/wix clean -df
git -C tools/perf/data clean -df
git -C ui/file_manager/internal clean -df
git -C ui/webui/internal clean -df
git -C webkit/data/bmp_decoder clean -df
git -C webkit/data/ico_decoder clean -df
git -C webkit/data/test_shell/plugins clean -df
git -C third_party/search_engines_data/resources clean -df
git -C third_party/speedometer/v3.1 clean -df
git -C third_party/webpagereplay clean -df
git -C third_party/compiler-rt/src clean -df
git -C third_party\dawn\third_party\webgpu-headers\src clean -df

pause
